# Generated by Django 4.2.1 on 2023-10-14 17:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Gestionnaire', 'Gestionnaire'), ('Agent CFC', 'Agent CFC'), ('Supperviseur', 'Supperviseur'), ('Administrateur', 'Administrateur')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField(unique=True)),
                ('Descrip_logement', models.TextField()),
                ('Vide', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_banque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Demandeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_paiement', models.CharField(choices=[('CASH', 'Cash'), ('CFC', 'CFC')], max_length=50)),
                ('Civilite', models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='M.', max_length=4)),
                ('Noms_demandeur', models.CharField(max_length=80)),
                ('Prenom_demandeur', models.CharField(max_length=80)),
                ('Date_de_naissance', models.DateField()),
                ('Situation_matrimoniale', models.CharField(choices=[('MA', 'Marié(e)'), ('VE', 'Veuf(ve)'), ('CE', 'Célibataire')], default='MA', max_length=4)),
                ('Adresse', models.CharField(blank=True, max_length=80, null=True)),
                ('Email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Telephone', models.IntegerField(blank=True, null=True, verbose_name='Téléphone')),
                ('Numero_identite', models.IntegerField(blank=True, null=True)),
                ('Numero_compte_bancaire', models.IntegerField(blank=True, null=True)),
                ('Mis_a_jour', models.DateTimeField(auto_now=True)),
                ('Publie_le', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('Etat_demandes', models.BooleanField(default=False)),
                ('info_cfc', models.CharField(choices=[('NT', 'Marié(e)'), ('FA', 'Veuf(ve)'), ('DEF', 'Célibataire')], default='NT', max_length=50)),
            ],
            options={
                'ordering': ['-Publie_le'],
            },
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_employeur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Logement_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ville', models.CharField(choices=[('Dla', 'Douala'), ('Yde', 'Yaoundé')], max_length=20)),
                ('Quartier', models.CharField(choices=[('Mbanga Bakoko', 'Mbanga Bakoko'), ('Olembé', 'Olembé')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_profession', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Revenu_mensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nature', models.CharField(blank=True, choices=[('S', 'Salaire'), ('A', 'Autres')], default='S', max_length=1)),
                ('Montant', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_ville', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pieces_Jointes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Demande_logement', models.ImageField(blank=True, null=True, upload_to='Demande_logement')),
                ('Cni_demandeur', models.ImageField(blank=True, null=True, upload_to='Cni_demandeur')),
                ('Acte_naissance', models.ImageField(blank=True, null=True, upload_to='Acte_naissance')),
                ('Certificat_celibat', models.ImageField(blank=True, null=True, upload_to='Certificat_celibat')),
                ('Attestation_travail', models.ImageField(blank=True, null=True, upload_to='Attestation_travail')),
                ('Attestation_presence_effective_cfc', models.ImageField(blank=True, null=True, upload_to='Attestation_presence_effective_cfc')),
                ('Bulletin_paie1_cfc', models.ImageField(blank=True, null=True, upload_to='Bulletin_paie_cfc')),
                ('Bulletin_paie2_cfc', models.ImageField(blank=True, null=True, upload_to='Bulletin_paie_cfc')),
                ('Bulletin_paie3_cfc', models.ImageField(blank=True, null=True, upload_to='Bulletin_paie_cfc')),
                ('Recu_paiement_frais_dossier', models.ImageField(blank=True, null=True, upload_to='Recu_paiement_frais_dossier')),
                ('Engagement_sur_honneur_occup_pers', models.ImageField(blank=True, null=True, upload_to='Engagement_sur_honneur_occup_pers')),
                ('Engagement_sur_honneur_payer_apport_perso_cfc', models.ImageField(blank=True, null=True, upload_to='Engagement_sur_honneur_payer_apport_perso_cfc')),
                ('Engagement_sur_honneur_payer_comptant_cfc', models.ImageField(blank=True, null=True, upload_to='Engagement_sur_honneur_payer_comptant_cfc')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_pieces_jointes', to='main.demandeur')),
            ],
        ),
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lettre', models.CharField(max_length=1)),
                ('bloc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.logement_social')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement_Financier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Montant', models.IntegerField()),
                ('date_de_fin', models.DateField()),
                ('Banque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.banque')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_engagement_financier', to='main.demandeur')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_logement', models.CharField(max_length=80)),
                ('Prix_vente', models.IntegerField()),
                ('Depot_garantie_disponible', models.BooleanField(default=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_engagement_client', to='main.demandeur')),
            ],
        ),
        migrations.CreateModel(
            name='Enfant_legitime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank=True, max_length=80, null=True)),
                ('Prenom', models.CharField(blank=True, max_length=80, null=True)),
                ('Sexe', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], default='M', max_length=1, null=True)),
                ('Date_naiss', models.DateField(blank=True, null=True)),
                ('Niveau_scolaire_ou_profession', models.CharField(blank=True, max_length=50, null=True)),
                ('Lieu_naiss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lieunaiss_enf', to='main.ville')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_parent', to='main.demandeur')),
            ],
        ),
        migrations.AddField(
            model_name='demandeur',
            name='Employeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employeur'),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='Lieu_de_Naissance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naiss_ho', to='main.ville'),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='Nom_banque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.banque'),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='Profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profession'),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='Ville_origine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorigine', to='main.ville'),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='createur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='createur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='revenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.revenu_mensuel'),
        ),
        migrations.CreateModel(
            name='Decision_comite_attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis_attribution', models.BooleanField(default=True, verbose_name="Avis d'attribution")),
                ('Commentaire', models.TextField(blank=True, null=True)),
                ('Pieces', models.ImageField(blank=True, null=True, upload_to='Decision')),
                ('Demandeur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandeur_decision', to='main.demandeur')),
                ('Numero_logement_attribue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.appartement')),
            ],
        ),
        migrations.CreateModel(
            name='Conjoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_conjoint', models.CharField(blank=True, max_length=80, null=True)),
                ('Prenom_conjoint', models.CharField(blank=True, max_length=80, null=True)),
                ('Date_naiss_conjoint', models.DateField()),
                ('Numero_identite_conjoint', models.IntegerField(blank=True, null=True)),
                ('Numero_compte_bancaire_conjoint', models.IntegerField(blank=True, null=True)),
                ('Cni', models.ImageField(upload_to='Cni_conjoint')),
                ('Lieu_naiss_conjoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lieunaiss', to='main.ville')),
                ('Nom_adresse_employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeur_conjoint', to='main.employeur')),
                ('Nom_banque_conjoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.banque')),
                ('Profession_conjoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_profession', to='main.profession')),
                ('Revenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.revenu_mensuel')),
                ('Ville_origine_conjoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vc_origine', to='main.ville')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_conjoint', to='main.demandeur')),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.demandeur'),
        ),
        migrations.AddField(
            model_name='appartement',
            name='immeuble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.immeuble'),
        ),
        migrations.CreateModel(
            name='Accord_cfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_de_conformilte', models.BooleanField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('Justificatif', models.ImageField(blank=True, null=True, upload_to='demandeok')),
                ('demande', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demande', to='main.demandeur')),
            ],
        ),
    ]
