# Generated by Django 4.2.1 on 2023-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjoint',
            name='Cni',
            field=models.ImageField(blank=True, null=True, upload_to='Cni_conjoint'),
        ),
    ]
